### ISSUE TITLE
how to format timebased axis

### ISSUE THREAD

**Issue by junhui** [stormpython/heatmap#40] opened 2016-09-14 21:36 UTC
When i use _Date Histogram_ as X axis like below:
![b](https://cloud.githubusercontent.com/assets/1891654/18530859/4b38470e-7a88-11e6-976e-ebe7f6fa3d4b.png)

the heatmap only show limited characters of the time:
![a](https://cloud.githubusercontent.com/assets/1891654/18530806/0e8022aa-7a88-11e6-8fb7-7b267a836ca6.png)

my full time example is: 
`
 "@timestamp": "2016-09-14T21:34:51.424Z"
`

is there anyway i can format the time in x axis?

thanks!

**Comment by stormpython** [comment] 2016-09-15 16:31
This is a duplicate of #28. Its currently on my roadmap to get fixed.

**Closed as completed by stormpython** 2016-09-15 16:31 UTC
