### ISSUE TITLE
plugin installation error using kibana 4.5.4

### ISSUE THREAD

**Issue by regel** [stormpython/heatmap#44] opened 2016-09-27 15:49 UTC
Hi,

I'm unable to install the plugin using master version, RHEL7 environment.

Is there another release I can test, other than master ?

Error:

$ bin/kibana --version
4.5.4
$ bin/kibana plugin -i heatmap -u https://github.com/stormpython/heatmap/archive/master.zip
Installing heatmap
Attempting to transfer from https://github.com/stormpython/heatmap/archive/master.zip
Transferring 1811145 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error Optimizations failure.

```
ERROR in ./installedPlugins/heatmap/public/heatmap.js
Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/src/ui/public/template_vis_type/template_vis_type in /opt/kibana/installedPlugins/heatmap/public
 @ ./installedPlugins/heatmap/public/heatmap.js 11:32-81

ERROR in ./installedPlugins/heatmap/public/heatmap.js
Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/src/ui/public/vis/schemas in /opt/kibana/installedPlugins/heatmap/public
 @ ./installedPlugins/heatmap/public/heatmap.js 12:24-49
```

$ rpm -qi elasticsearch
Name        : elasticsearch
Version     : 2.4.0
Release     : 1
Architecture: noarch
Install Date: Thu 22 Sep 2016 01:41:14 PM EDT
Group       : Application/Internet
Size        : 30567803
License     : (c) 2009
Signature   : RSA/SHA1, Mon 29 Aug 2016 05:24:45 AM EDT, Key ID d27d666cd88e42b4
Source RPM  : elasticsearch-2.4.0-1.src.rpm
Build Date  : Mon 29 Aug 2016 05:24:43 AM EDT
Build Host  : vagrant-ubuntu-trusty-64
Relocations : /usr 
Packager    : Elasticsearch
Summary     : Distribution: RPM
Description :
Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html

$ rpm -qi kibana
Name        : kibana
Version     : 4.5.4
Release     : 1
Architecture: x86_64
Install Date: Thu 22 Sep 2016 01:41:56 PM EDT
Group       : default
Size        : 124951303
License     : Apache 2.0
Signature   : RSA/SHA1, Wed 03 Aug 2016 10:48:34 AM EDT, Key ID d27d666cd88e42b4
Source RPM  : kibana-4.5.4-1.src.rpm
Build Date  : Tue 02 Aug 2016 11:09:35 AM EDT
Build Host  : kbnbuild-VirtualBox
Relocations : / 
Packager    : Kibana Team info@elastic.co
Vendor      : Elasticsearch, Inc.
URL         : https://www.elastic.co
Summary     : Explore and visualize your Elasticsearch data
Description :
Explore and visualize your Elasticsearch data

**Comment by stormpython** [comment] 2016-09-27 16:56
Duplicate of #43.

**Closed as completed by stormpython** 2016-09-27 16:56 UTC
